### ISSUE TITLE
The POM for org.apache.flink:flink-connector-kinesis_2.11:jar:1.8.2 is missing, no dependency information available

### ISSUE THREAD

**Issue by arjunsk** [aws-samples/amazon-kinesis-analytics-taxi-consumer#3]
In the current maven repository, there is no mention of the 1.8.2 version. Please verify the flink version used.

**Comment by autoincr** [comment]
Flink Kinesis connector repo is no longer valid: http://maven.icm.edu.pl/artifactory/repo/org/apache/flink/flink-connector-kinesis_2.11/1.8.0

**Comment by autoincr** [comment]
Should we be using 
`    <flink.version>1.10.0</flink.version>`
in AWS KDA ?

The AWS KDA is having the flink version configured to 1.8  though.

**Comment by autoincr** [comment]
Closing this issue, since solved.

"The flink-connector-kinesis_2.11 artifact is not deployed to Maven central as part of Flink releases because of the licensing issue. Therefore, you need to build the connector yourself from the source."

Reference: https://ci.apache.org/projects/flink/flink-docs-release-1.7/dev/connectors/kinesis.html
